<a href="https://colab.research.google.com/github/AzadMehedi/ML-Algorithoms/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [15]:
url = 'https://raw.githubusercontent.com/FazlyRabbiBD/Data-Science-Book/master/data-drugs.csv'
df = pd.read_csv(url)
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [16]:
# setting dummy vaalues to the categorical variable  (Sex, BP, Cholesterol) using map function

d = {'M':1, 'F':0}
df['Sex'] = df['Sex'].map(d)

d = {'NORMAL':1, 'LOW':0, 'HIGH':2}
df['BP'] = df['BP'].map(d)

d = {'NORMAL':0, 'HIGH':1}
df['Cholesterol'] = df['Cholesterol'].map(d)

In [17]:
df.sample(10)

     Age  Sex  BP  Cholesterol  Na_to_K   Drug
131   52    1   0            0   32.922  drugY
53    24    0   2            0   18.457  drugY
6     49    0   1            1   16.275  drugY
106   22    1   1            1   11.953  drugX
17    43    1   2            1   13.972  drugA
170   28    0   1            1   12.879  drugX
93    42    0   0            0   29.271  drugY
11    34    0   2            0   19.199  drugY
70    70    1   2            1   13.967  drugB
149   22    1   0            1    8.151  drugC

In [18]:
# feature and target variabe define
features = ['Age', 'Sex', 'BP', 'Cholesterol','Na_to_K']
x = df[features]
y = df['Drug']

In [19]:
# train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

# we will use 10 trees for for a random forest
rf = RandomForestClassifier(n_estimators=10, max_depth=5, random_state=0)
rf.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=10, random_state=0)

In [24]:
# prediction and accuracy check

predictions = rf.predict(x_test)
print('Classification Report \n:', classification_report(y_test, predictions))
print('\n Accuracy Score: ', accuracy_score(y_test, predictions))
print('\n Confusion Matrix \n:', confusion_matrix(y_test, predictions))

Classification Report
:               precision    recall  f1-score   support

       drugA       0.88      1.00      0.93         7
       drugB       1.00      0.86      0.92         7
       drugC       1.00      0.33      0.50         6
       drugX       0.73      0.92      0.81        12
       drugY       0.97      1.00      0.98        28

    accuracy                           0.90        60
   macro avg       0.91      0.82      0.83        60
weighted avg       0.92      0.90      0.89        60


 Accuracy Score:  0.9

 Confusion Matrix
: [[ 7  0  0  0  0]
 [ 1  6  0  0  0]
 [ 0  0  2  4  0]
 [ 0  0  0 11  1]
 [ 0  0  0  0 28]]

### model accuracy is 90%